# fly.toml app configuration file generated for homolog-tts-service on 2025-08-22T20:45:28-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'homolog-tts-service'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
